title: Data Frittata
description: >
  Problem solving: from academia to data engineering, science and business.
permalink: ':title/'
baseurl: ""
url: ""
site-twitter:

# Author Settings
author: Dmitry Smirnov
author-img: square_photo.jpg
about-author: Who am I?
social-twitter:
social-facebook:
social-github: drapadubok
social-linkedin: dmismirnov
social-email: dmitry.smirnov@fourkind.com

# Disqus
discus-identifier:

# Tracker
analytics:

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
